
BENDERS_OPTIONS_MACRO(LOG_LEVEL, int, 1)
BENDERS_OPTIONS_MACRO(MAX_ITERATIONS, int, -1)
BENDERS_OPTIONS_MACRO(GAP, double, 1e-6)
BENDERS_OPTIONS_MACRO(AGGREGATION, bool, false)
BENDERS_OPTIONS_MACRO(OUTPUTNAME, std::string, "benders_output.csv")
BENDERS_OPTIONS_MACRO(TRACE, bool, true)
BENDERS_OPTIONS_MACRO(DELETE_CUT, bool, true)
BENDERS_OPTIONS_MACRO(SLAVE_WEIGHT, std::string, "UNIFORM")